FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/", "./src/"]
COPY ["tests/", "./tests/"]
COPY ["TodoTaskAPI.sln", "./"]
RUN dotnet restore "tests/TodoTaskAPI.IntegrationTests/TodoTaskAPI.IntegrationTests.csproj"
RUN dotnet build "tests/TodoTaskAPI.IntegrationTests/TodoTaskAPI.IntegrationTests.csproj" -c Release --no-restore

FROM build AS test
WORKDIR /src/tests/TodoTaskAPI.IntegrationTests
CMD ["dotnet", "test", "--no-build", "--configuration", "Release"]